name: CI

on: [push, pull_request]

jobs:
  code_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Setup
        run: python -m pip install -r requirements-dev.txt

      - name: Run Black
        run: black . --check

      - name: Run isort
        run: isort . --check
